name: conda-slicemypdf
channels:
  - conda-forge
  - rapidsai
  - nvidia
  - numba
  - defaults
  - jacksongs
  - tc06580
dependencies:
  - numpy=1.19.4
  - scipy=1.6.0
  - pandas=1.2.0
  - pip=20.3
  - python=3.9.0
  - yaml=0.2.5
  - poppler=0.89.0
  - geopandas=0.9.0
  - ipykernel=6.0.1
  - delegator=0.1.0
  - pypdf2=1.26.0
  - pigz=2.6
  - lxml=4.6.3
  - pillow=8.1.2
  - wand=0.6.5
  - pdfminer
  - pip:
    - tqdm
    - xmltodict
    - pgeocode
    - glob2
    - pandarallel==1.5.1
    - PyYAML
    - PyMuPDF
    - py7zr
    - pycountry
    - geoparsepy
    - geograpy3